### ISSUE TITLE
New awesome repo

### ISSUE THREAD

**Issue by AbdAlghaniAlbiek** [tomzorz/awesome-uwp#19]
Can you add these repos to your list .. it's awesome 😉
https://github.com/microsoft/Xaml-Controls-Gallery
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit
https://github.com/jordan-thoms/Retrofit.Net

**Comment by tomzorz** [comment]
Added the xaml controls gallery, the other two are either generic .net or WPF :)
