### ISSUE TITLE
grab any usful links (if any) from my list

### ISSUE THREAD

**Issue by 10Dev** [tomzorz/awesome-uwp#9]
Grab any usful links (if any) from my list:

https://github.com/10UWP/The-UWP-Tools-List

Pick through them to meet your "Asesome" criteria since I am not testing or verifying anything on my list so there could be a lot of useless or marginal projects there

**Comment by tomzorz** [comment]
The "awesome" is not really a criteria, as I was just following the naming pattern :) Feel free to submit a PR with the additions you'd like to see.
